### PR TITLE
ipv6: remove some code duplication

### PR DESCRIPTION
**Pull request by OlegHahm**
I think checking for the MTU once is enough. Additionally, I removed the need for two version of the `_send_to_iface()` function.

### CODE REVIEW

**Comment by OlegHahm** [comment]
oops, something got lost, hang on!

**Comment by OlegHahm** [comment]
fixed

**Comment by authmillenon** [comment]
Mh, but now it goes to all this trouble only to realize in the very end, that it is not working :-/

**Comment by authmillenon** [comment]
But I take it anyway.

**Comment by OlegHahm** [comment]
I know, but I prefer having some overhead over the code duplication.

**Pull request merged**
